### ISSUE TITLE
"Our guide" link navigates to wrong url address

### ISSUE THREAD

**Issue by gokhanamal** [socketkit/bugs#7]
The guide link doesn't work, it navigates to "https://socketkit.comblog/guides/how-to-integrate-appstore-connect" address <img width="389" alt="Screen Shot 2021-04-07 at 09 19 43" src="https://user-images.githubusercontent.com/21364542/113819772-72a6aa80-9782-11eb-8d62-3bd332f9cc7f.png">

**Comment by anonrig** [comment]
Hi @gokhanamal 

Thank you for your feedback. I just fixed the link. If the bug persists, please add a comment to this issue.
